next.config.js
rewrites-redirects.json

This PR removes obsolete store redirects and some comments from next.config.js as well.

Remove obsolete redirects and comments

---

public/locales/en/common.json
src/components/header/HeaderList.js
src/components/header/HeaderListNetwork.js

Add the Ramps item (https://solana.com/solanaramp) in the main Network dropdown.

Add the Ramps item in the Network dropdown

---

public/locales/ar/common.json
public/locales/de/common.json
public/locales/el/common.json
public/locales/en/common.json
public/locales/es/common.json
public/locales/fi/common.json
public/locales/fr/common.json
public/locales/hi/common.json
public/locales/id/common.json
public/locales/it/common.json
public/locales/ja/common.json
public/locales/ko/common.json
public/locales/nl/common.json
public/locales/pl/common.json
public/locales/pt/common.json
public/locales/ru/common.json
public/locales/tr/common.json
public/locales/uk/common.json
public/locales/vi/common.json
public/locales/zh/common.json
src/components/ramps/RampFilter.jsx
src/components/ramps/RampFilter.module.scss
src/components/ramps/Ramps.jsx
src/components/ramps/Ramps.module.scss
src/components/ramps/RampsCard.jsx
src/components/ramps/RampsCard.module.scss

- a ramp card is fully clickable now
- some placeholder strings do not have to live in the locales at all
- style updates
- add support to filter sidebar checkboxes lists

/solanaramp page improvements

---

rewrites-redirects.json

Solang is deprecated so this is a redirect to our easiest hello world guide

Redirect solang guide to hello world guide

---

public/locales/ar/common.json
public/locales/de/common.json
public/locales/el/common.json
public/locales/en/common.json
public/locales/es/common.json
public/locales/fi/common.json
public/locales/fr/common.json
public/locales/hi/common.json
public/locales/id/common.json
public/locales/it/common.json
public/locales/ja/common.json
public/locales/ko/common.json
public/locales/nl/common.json
public/locales/pl/common.json
public/locales/pt/common.json
public/locales/ru/common.json
public/locales/tr/common.json
public/locales/uk/common.json
public/locales/vi/common.json
public/locales/zh/common.json
src/components/breakpoint/BreakpointHeader.jsx

Add Speakers and Sponsors to Breakpoint menu.

Update the Breakpoint menu

---

src/utils/builderConfigs.js

Set localized true for even more inputs in Builder.

localized: true for even more Builder inputs

---

src/pages/developers/courses/index.tsx
src/types/content-api.ts

Use `isHidden` to hide Unboxed courses that need an update after https://github.com/solana-foundation/developer-content/pull/316 is merged.
(Draft, but ready to go once PR above is merged)

Hide outdated content from UI

---

public/locales/ar/common.json
public/locales/de/common.json
public/locales/el/common.json
public/locales/en/common.json
public/locales/es/common.json
public/locales/fi/common.json
public/locales/fr/common.json
public/locales/hi/common.json
public/locales/id/common.json
public/locales/it/common.json
public/locales/ja/common.json
public/locales/ko/common.json
public/locales/nl/common.json
public/locales/pl/common.json
public/locales/pt/common.json
public/locales/ru/common.json
public/locales/tr/common.json
public/locales/uk/common.json
public/locales/vi/common.json
src/components/breakpoint/BreakpointHeader.jsx

This ads the Schedule link and reorders the Breakpoint menu items.

Breakpoint menu update

---

next-env.d.ts
rewrites-redirects.json
src/pages/developers/cookbook/[[...slug]].tsx
src/pages/developers/courses/[course]/[lesson]/index.tsx
src/pages/developers/guides/[...slug].tsx
src/pages/developers/resources/[...slug].jsx
src/pages/docs/[[...slug]].tsx
src/pages/docs/rpc/[[...slug]].tsx
src/utils/contentApi.ts

- update/fix redirects
- actually use the seo title in the seo metadata
- the `next-env.d.ts` seems to get updated on every `yarn dev`, so I comitted it
- corrected the "edit on github" links

various dev content fixes

---

next-env.d.ts
src/pages/breakpoint/side-events.js

- Fix path for the /breakpoint/side-event social card
- Revert next-env.d.ts

Fix path for side events social card

---

public/locales/ar/common.json
public/locales/de/common.json
public/locales/el/common.json
public/locales/en/common.json
public/locales/es/common.json
public/locales/fi/common.json
public/locales/fr/common.json
public/locales/hi/common.json
public/locales/id/common.json
public/locales/it/common.json
public/locales/ja/common.json
public/locales/ko/common.json
public/locales/nl/common.json
public/locales/pl/common.json
public/locales/pt/common.json
public/locales/ru/common.json
public/locales/tr/common.json
public/locales/uk/common.json
public/locales/vi/common.json
src/pages/developers/index.jsx

Better localization #45

---

public/locales/ar/common.json
public/locales/de/common.json
public/locales/el/common.json
public/locales/en/common.json
public/locales/es/common.json
public/locales/fi/common.json
public/locales/fr/common.json
public/locales/hi/common.json
public/locales/id/common.json
public/locales/it/common.json
public/locales/ja/common.json
public/locales/ko/common.json
public/locales/nl/common.json
public/locales/pl/common.json
public/locales/pt/common.json
public/locales/ru/common.json
public/locales/tr/common.json
public/locales/uk/common.json
public/locales/vi/common.json
public/locales/zh/common.json
src/components/developers/sections/DevelopersDocumentsSection/DevelopersDocumentsSection.jsx
yarn.lock

- update the docs link on the /developers page to be the Anchor framework
- updated translations to reflect

refactor: changed link

---

src/components/developers/sections/DevelopersCoursesSection/DevelopersCoursesSection.jsx

Update bootcamp link to the [2024 Bootcamp](https://www.youtube.com/watch?v=amAq-WHAFs8&list=PLilwLeBwGuK7HN8ZnXpGAD9q6i4syhnVc).

feat: new bootcamp link

---

package.json
yarn.lock

Downgrade the Nextjs version for now to try to overcome a random issue with the /docs* pages.
Related #44.

Downgrade Nextjs version for now

---

src/pages/news/feed.js

Fix title being broken in /news/feed due to a recent Builder API response change. Also remove item content from the feed due to being error prone.

Fix response title in /news/feed

---

next.config.js

Better catch Builder redirect errors to prevent the build from failing.

Better catch redirect errors

---

rewrites-redirects.json

Add custom `/verified-builds` redirect.

Add redirect

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.prettierignore

- added a github PR template
- added github templates to the prettier ignore
- added empty spaced in the issues template to make it nicer for people to open issues

[chore] added GitHub PR template

---

content/guides/getstarted/intro-to-ai.mdx
content/guides/getstarted/meta.json

There was not AI guide yet. 
Added an AI guide with some examples and a list of possible tools.

Add Ai tools guide

---

public/locales/en/common.json
src/components/ai/AiCard.jsx

Add link to The Grid resource to highlight more Solana projects
Fixes #167

Add link to thegrid resource

---

src/app/[locale]/developers/developers.tsx

StackExchange CTA just being the title on the developer homepage is not great. Make it more actionable

chore: update stackexchange cta

---

public/locales/el/common.json
public/locales/en/common.json
public/locales/fi/common.json
public/locales/hi/common.json
public/locales/ja/common.json
public/locales/ko/common.json
public/locales/nl/common.json
public/locales/ru/common.json
public/locales/tr/common.json
public/locales/uk/common.json
public/locales/zh/common.json

Lots of tabs on developer pages. RPC API is pretty verbose
Make it just `API`

chore: Update RPC API to just API

---

src/components/wallets/WalletCard.jsx
src/components/wallets/Wallets.jsx
src/data/wallets/wallet-data.js

The /solana-wallets page was not sorted, everything being added in chronological order
The wallets data is now randomized on the client-side.

Randomize the wallets data

---

content/cookbook/wallets/restore-from-mnemonic.mdx
content/guides/getstarted/intro-to-ai.mdx

formant - format 
repetition removed: 
which has integrated AI features and can help you with any errors you may encounter.

spelling and grammar issues

---

.prettierrc
CONTRIBUTING.md
README.md
src/markdown/learn/blockchain-basics.md
src/markdown/learn/dao.md
src/markdown/learn/nfts.md
src/markdown/learn/payments.md

- Add `"proseWrap": "always"` to `.prettierc` so autoformat on save and wrap lines in markdown files
- Run prettier updating existing .md files

docs: add proseWrap to prettier config

---

content/docs/intro/installation.mdx

- update installation page, add anchor cli section
- add quick installation curl command to install all dependencies using [this script](https://github.com/solana-developers/solana-install/blob/main/install.sh)

docs: update installation page

---

content/docs/intro/installation.mdx

- add `--proto '=https' --tlsv1.2` to quick install command

docs: update quick install command

---

src/data/wallets/wallet-data.js

chore: fix typo

---

content/cookbook/programs/read-accounts.mdx
content/cookbook/tokens/get-nft-owner.mdx
content/cookbook/wallets/generate-mnemonic.mdx

indicing - indexing
whilst - while
make is easy - make it easy

chore: fix typos 

---

content/cookbook/programs/cross-program-invocation.mdx
content/cookbook/tokens/manage-wrapped-sol.mdx

Lets - Let's 
just like - just is like

fix spelling errors

---

rewrites-redirects.mjs

add redirects for moved docs pages

docs: redirects

---

content/docs/index.mdx

- add Jona's 2048 to /docs as demonstration of speed of Solana transactions to new users
- games are fun

docs: add 2048 game

---

src/components/wallets/Wallets.jsx
src/components/wallets/WalletsLayout.jsx
src/pages/[locale]/solana-wallets.js

Fix inconsistent randomization and randomize wallet data during static generation instead

Randomize data during static generation instead

---

content/docs/index.mdx
src/app/globals.css

- update bullet points links on /docs with fumadocs cards
- remove underline on-hover for links

docs: update bullet points links on /docs with fumadocs cards

---

content/docs/index.mdx

- hide the game in an Accordion so it takes less space

docs: Move 2048 game into Accordion

---

src/app/[locale]/developers/cookbook/layout.tsx
src/app/[locale]/developers/courses/[course]/[lesson]/layout.tsx
src/app/[locale]/developers/guides/[...slugs]/layout.tsx
src/app/[locale]/docs/(main)/layout.tsx
src/app/[locale]/docs/rpc/layout.tsx
src/app/[locale]/docs/toolkit/layout.tsx
src/app/[locale]/layout.tsx
src/app/components/inkeep-script.tsx

- Move Inkeep script for AI Chat widget to layout of each respective route to limit where the widget appears to only pages from `/content`

docs: move Inkeep script to individual route layout

---

content/cookbook/transactions/send-sol.mdx

added cookbook snippets for sending sol using the new javascript client

[cookbook] send sol

---

content/cookbook/accounts/calculate-rent.mdx
content/cookbook/accounts/get-account-balance.mdx
content/cookbook/accounts/meta.json
content/cookbook/development/connect-environment.mdx
content/cookbook/development/load-keypair-from-file.mdx
content/cookbook/development/meta.json
content/cookbook/development/test-sol.mdx
content/cookbook/index.mdx
content/cookbook/meta.json
content/cookbook/programs/meta.json
content/cookbook/tokens/meta.json
content/cookbook/transactions/add-memo.mdx
content/cookbook/transactions/meta.json
content/cookbook/wallets/create-keypair.mdx
content/cookbook/wallets/meta.json
content/cookbook/wallets/restore-keypair.mdx

update multiple cookbook pages to use the new javascript client:
- calculate rent
- get account balance
- connect environment
- load keypair from file
- test sol (aka airdrop)
- add memo instruction
- create a keypair
- restore a keypair
other updates:
- update cookbook index to list the language for the code snippets available
- made all cookbook sidebars collapsed by default

[cookbook] multiple pages for new javascript client

---

content/docs/index.mdx

- adjust width to made game size responsive to mobile screens

docs: fix 2048 iframe width for mobile

---

content/docs/intro/installation.mdx

- add description to wsl instructions to try quick install command after installing wsl
- update with codehike terminal and inline code snippets

docs: update install page

---

content/docs/references/feature-gates/b7h2caeia4zfcpe3qcgmqbiwibtwrdbrbsj1dy6ktxbq.mdx
content/docs/references/feature-gates/meta.json
content/docs/references/feature-gates/tsynmcspg4xficj1v3tdb4c7crmr5tsbhlz4sf7rrna.mdx
content/docs/references/meta.json

Missing docs for feature gates
Adds descriptions for upcoming mainnet feature gates:
- tSynMCspg4xFiCj1v3TDb4c7crMR5tSBhLz4sF7rrNA
- B7H2caeia4ZFcpE3QcgMqbiWiBtWrdBRBSJ1DY6Ktxbq

Add feature gate descriptions

---

content/docs/references/feature-gates/b7h2caeia4zfcpe3qcgmqbiwibtwrdbrbsj1dy6ktxbq.mdx
content/docs/references/feature-gates/gjvdwrkupndk9qak4vsu4g1n41qnxhy1hevjf8kz45mq.mdx
content/docs/references/feature-gates/meta.json

feature gate description was wrong for sBPF failure - there is no impact.
Only actionable impact is for direct mapping - developers should avoid writing to read-only accounts in their programs.
Fixes #

Cleanup impact for cu metering simd, add direct mapping actionable

---

.gitignore
content/docs/intro/quick-start/cross-program-invocation.mdx
content/docs/intro/quick-start/deploying-programs.mdx
content/docs/intro/quick-start/index.mdx
content/docs/intro/quick-start/program-derived-address.mdx
content/docs/intro/quick-start/reading-from-network.mdx
content/docs/intro/quick-start/writing-to-network.mdx

- update quickstart section with codehike components and annotations

docs: update quickstart section

---

content/docs/programs/rust/index.mdx

The official code example for the testing of hello_world program was not working.
Fixed transaciton
Fixes #
Fixed the code sample to compile with the latest version of rust and solana sdk

fix: add working example for hello world example

---

content/cookbook/wallets/check-publickey.mdx
content/cookbook/wallets/create-keypair.mdx
content/cookbook/wallets/generate-mnemonic.mdx
content/cookbook/wallets/restore-from-mnemonic.mdx
content/cookbook/wallets/restore-keypair.mdx
content/cookbook/wallets/sign-message.mdx
content/cookbook/wallets/verify-keypair.mdx

Update the wallets section to include Solana rust client

docs: Update wallets section snippets in cookbook

---

src/app/components/code/callout.client.tsx
src/components/blog/Pagination.js

changed:
trasparent - transparent
seperatorClassname - separatorClassname

spelling issues

---

content/guides/advanced/exchange.mdx

- Add example with transaction metadata with tooltips explainations

docs: add example to exchange deposit section

---

rewrites-redirects.mjs

add an official redirect to the Skyline calendar

feat: added skyline redirect

---

content/docs/references/feature-gates/consume-cus-on-sbpf-failure.mdx
content/docs/references/feature-gates/direct-mapping.mdx
content/docs/references/feature-gates/meta.json
content/docs/references/feature-gates/reserve-minimal-cus-for-builtins.mdx
content/docs/references/feature-gates/tsynmcspg4xficj1v3tdb4c7crmr5tsbhlz4sf7rrna.mdx

Feature gate titles truncated in OG image previews
Remove feature gate key from titles
Fixes #

Update feature gate page titles

---

llmtxt-generator.py
public/llms.txt

Want to track effectiveness of llms.txt file for AI traffic
- Adds UTM params to LLMs.txt file
- Fixes guides & courses links
Fixes #

Add llms txt utm

---

content/docs/meta.json
content/docs/tokens/basics/create-mint.mdx
content/docs/tokens/basics/create-token-account.mdx
content/docs/tokens/basics/index.mdx
content/docs/tokens/basics/meta.json
content/docs/tokens/basics/mint-tokens.mdx
content/docs/tokens/basics/transfer-tokens.mdx
content/docs/tokens/extensions.mdx
content/docs/tokens/index.mdx
content/docs/tokens/meta.json
source.config.ts
src/app/[locale]/docs/(main)/docs.tsx
src/app/globals.css
src/app/mdx-components.tsx

- add minimal tokens section to docs as starting point to expand on
- update docs page css

docs: add tokens section to docs

---

content/docs/intro/installation.mdx

- update the quick install command with cloudflare worker to track analytics
```sh
curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash
```

docs: update solana install with cloudflare worker

---

src/components/accelerate/AccelerateNavButton.module.scss

Small design changes
Request was to remove background color from 2 buttons located in the Desktop header
Fixes #
Changed style in Sass file for those buttons and added colored bottom border on hover

Remove background from header buttons

---

src/app/components/inkeep/inkeep-searchbar.tsx
src/components/Header.js

- Dynamic import of Inkeep Searchbar to resolve issue where page router pages error:
https://solana-7bq7p8yo3-solana-foundation.vercel.app/solutions/token-extensions

docs: Dynamic import Inkeep Searchbar

---

content/courses/intro-to-solana/intro-to-reading-data.mdx

Fixes # added - "operations on the Solana blockchain, such as staking for network security and governance participation"

completed a sentence

---

content/docs/clients/game-sdks.mdx
content/docs/clients/meta.json
content/guides/games/meta.json
rewrites-redirects.mjs

There was no meta file for the games section. 
Added redirect for game sdks 
Added meta file for game section

Added games meta file and added redirect for game sdks

---

src/scss/_solana.scss

Prevent long links from breaking the layout
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

Prevent long links from breaking the layout

---

content/cookbook/accounts/calculate-rent.mdx
content/cookbook/accounts/create-account.mdx
content/cookbook/accounts/create-pda-account.mdx
content/cookbook/accounts/get-account-balance.mdx

- add rust snippets to get minimum amount for rent
- add rust snippets to get account balance
- add rust snippets to create account on client side
- create pda rust client snippets

docs: Rust snippets; get balance and rent cost; create account.

---

content/guides/advanced/verified-builds.mdx

remove duplicate section
Duplicate text / command.
Removes duplicate text/command.
Fixes #

docs: Update verified-builds.mdx

---

content/cookbook/tokens/create-token-account.mdx

added snippet for creating ata

[cookbook] create ata

---

content/cookbook/tokens/create-mint-account.mdx

added snippets for creating tokens

[cookbook] create token

---

content/cookbook/transactions/add-priority-fees.mdx

- added snippet for adding a priority fee using gill. included two both options
- update the code blocks to use the CodeTabs

[cookbook] add a priority fee

---

content/docs/clients/game-sdks.mdx
content/docs/index.mdx

- Add document for Solana C SDK
- Add document for Unreal SDK by Varmeta

docs: Solana-C SDK, Unreal SDK by VARMETA

---

content/courses/program-optimization/program-architecture.mdx

Remove repetitive text
(the 'solana account ACCOUNT_KEY' you'd get a data dump like the following) part repeats twice.
Remove repetitive text
Fixes #
Remove repetitive text

Fix program-architecture.mdx content

---

content/cookbook/development/load-keypair-from-file.mdx
content/cookbook/wallets/check-publickey.mdx
content/cookbook/wallets/restore-keypair.mdx

- load keypair/signer from file with gill
- simplified base58 keypair example
- fix a few typos on the pubkey check

[cookbook] keys

---

content/docs/clients/game-sdks.mdx
content/guides/getstarted/intro-to-ai.mdx

Having a hackathon intro tomorrow and wanted to show this agent powered crossmint amazon example as well.

Add Crossmint example

---

content/guides/getstarted/solana-token-airdrop-and-faucets.mdx

Adding a new devnet faucet
Adding a new devnet faucet
Fixes #

Add devnetfaucet.org

---

content/docs/rpc/http/getslotleaders.mdx

Reference: https://github.com/anza-xyz/agave/blob/a080c4bb157f48b268b74cf5dd2f3de39db7dc5d/rpc/src/rpc.rs#L3057-L3062

Note that slot/limit are not optional in `getSlotLeaders()`

---

content/docs/index.mdx

- add a vercel deployment demo to docs, enable users to get a functional program/frontend in one click
- basic counter program built using anchor framework

docs: add vercel deploy demo

---

content/docs/clients/game-sdks.mdx

Updating links for Thugz Blockchain Plugin (Unreal SDK) and adding documentation link.
Old links for Thugz Blockchain Plugin
Updated link for the Plugin page on the new FAB platform
Updated link for the Github Repository
New link for Documentation

Update game-sdks.mdx for Thugz by Tchiki

---

package.json
src/app/[locale]/layout.tsx
src/app/components/posthog/PostHogProvider.tsx
yarn.lock

- add posthog to docs for analytics

docs: add posthog to docs

---

.env.example
src/app/components/posthog/PostHogProvider.tsx

- move posthog key to env to avoid collecting data during local dev

docs: update posthog

---

content/docs/rpc/http/gettokenaccountsbydelegate.mdx
content/docs/rpc/json-structures.mdx
src/app/globals.css

Make fixes to rpc page mentioned in following PR:
- https://github.com/solana-foundation/solana-com/pull/364
- https://github.com/solana-foundation/solana-com/pull/365
Fixing in new PR due to updated rpc UI.
Also update css on docs page so rpc UI displays with more width

docs: rpc page fixes

---

src/pages/[locale]/edit-symbol.js

Block search indexing for this specific page

Block search indexing for this specific page

---

src/pages/[locale]/accelerate/AcceleratePage.js
src/pages/[locale]/accelerate/accelerate.module.scss

1. Fixed a bunch of copy + links
2. Fixed a broken get started button that was breaking due a conflicting css property

copy changes + button fix

---

content/docs/rpc/websocket/logssubscribe.mdx

I'm pretty sure these are non-nullable.
https://github.com/anza-xyz/agave/blob/135d3f8e31d6a2e2c970c76fc56f4fbcd4e052ab/rpc-client-types/src/response.rs#L244

Mark the logs in the logs subscription as non-nullable

---

content/cookbook/accounts/calculate-rent.mdx
content/cookbook/accounts/create-account.mdx
content/cookbook/accounts/create-pda-account.mdx
content/cookbook/accounts/get-account-balance.mdx
content/cookbook/development/connect-environment.mdx
content/cookbook/development/load-keypair-from-file.mdx
content/cookbook/development/subscribing-events.mdx
content/cookbook/transactions/add-memo.mdx
content/cookbook/transactions/add-priority-fees.mdx
content/cookbook/transactions/send-sol.mdx

add rust snippets for development section

docs: add rust snippets for development section

---

src/components/accelerate/AccelerateSpeakers.module.scss
src/components/accelerate/AccelerateSpeakers.tsx

Request for slider to have auto-slide functionality
Added autoplay prop
Added infinity prop
Fixed speaker image for responsive
Fixes #

add autoplay to speakers slider - fix responsive

---

content/docs/tokens/index.mdx

Add back `spl-token` cli examples to token page.

docs: add back token cli examples

---

content/cookbook/tokens/approve-token-delegate.mdx
content/cookbook/tokens/burn-tokens.mdx
content/cookbook/tokens/close-token-accounts.mdx
content/cookbook/tokens/create-mint-account.mdx
content/cookbook/tokens/create-nft.mdx
content/cookbook/tokens/create-token-account.mdx
content/cookbook/tokens/fetch-all-nfts.mdx
content/cookbook/tokens/fetch-nft-metadata.mdx
content/cookbook/tokens/get-all-token-accounts.mdx
content/cookbook/tokens/get-nft-owner.mdx
content/cookbook/tokens/get-token-account.mdx
content/cookbook/tokens/get-token-balance.mdx
content/cookbook/tokens/get-token-mint.mdx
content/cookbook/tokens/manage-wrapped-sol.mdx
content/cookbook/tokens/mint-tokens.mdx
content/cookbook/tokens/revoke-token-delegate.mdx
content/cookbook/tokens/set-update-token-authority.mdx
content/cookbook/tokens/transfer-tokens.mdx

docs: add Rust snippets for fungible token examples

docs: add rust snippets for token examples

---

src/app/[locale]/docs/api/route.tsx
src/app/components/code/code.runable.tsx

- move run button into accordion
- make accordion default open
- parse program logs

docs: update mirror ui

---

src/app/[locale]/docs/api/route.tsx
src/app/components/code/code.runable.tsx

- make logs look similar to explorer

docs: update mirror program log parse

---

content/docs/en/core/accounts.mdx
content/docs/en/core/fees.mdx
content/docs/en/core/pda.mdx
content/docs/en/core/programs.mdx
content/docs/en/core/transactions.mdx

- update accounts, transaction, fee, program pages

docs: update core pages

---

content/docs/en/core/accounts.mdx
content/docs/en/core/fees.mdx
content/docs/en/core/transactions.mdx
content/docs/en/tokens/extensions/confidential-transfer/apply-pending-balance.mdx
content/docs/en/tokens/extensions/confidential-transfer/create-mint.mdx
content/docs/en/tokens/extensions/confidential-transfer/create-token-account.mdx
content/docs/en/tokens/extensions/confidential-transfer/deposit-tokens.mdx
content/docs/en/tokens/extensions/confidential-transfer/index.mdx
content/docs/en/tokens/extensions/confidential-transfer/transfer-tokens.mdx
content/docs/en/tokens/extensions/confidential-transfer/withdraw-tokens.mdx
src/app/[locale]/docs/api/route.tsx

parse http://localhost:8899 to mirror url to run code in docs, while keeping snippet simply to copy/paste to run locally on solana-test-validator

docs: parse http://localhost:8899 to mirror url

---

package.json
src/components/accelerate/AccelerateHeader.jsx
src/components/accelerate/AccelerateHeader.module.scss

Request for new link in Accelerate header
Added new empty link
To do: URL needs to be added on desktop header + mobile menu
Fixes #
Header responsive, link wrapping

added new link to header and mobile menu - fixed header responsive

---

content/docs/en/core/accounts.mdx
content/docs/en/tokens/basics/create-mint.mdx
content/docs/en/tokens/basics/create-token-account.mdx
content/docs/en/tokens/basics/mint-tokens.mdx
content/docs/en/tokens/basics/transfer-tokens.mdx

- update accounts page to include Kit and Rust snippets

docs: update accounts page

---

content/docs/en/core/accounts.mdx
content/docs/en/core/transactions.mdx

- update transactions page, add kit and rust code examples

docs: update transactions page

---

content/docs/en/intro/installation.mdx

Include installation instructions for RHEL derivatives docs

docs: update installation to include RHEL distros

---

content/docs/en/rpc/http/getaccountinfo.mdx
content/docs/en/rpc/http/getbalance.mdx
content/docs/en/rpc/http/getblock.mdx
content/docs/en/rpc/http/getblockcommitment.mdx
content/docs/en/rpc/http/getblockheight.mdx
content/docs/en/rpc/http/getblockproduction.mdx
content/docs/en/rpc/http/getblocks.mdx
content/docs/en/rpc/http/getblockswithlimit.mdx
content/docs/en/rpc/http/getblocktime.mdx
content/docs/en/rpc/http/getclusternodes.mdx
content/docs/en/rpc/http/getepochinfo.mdx
content/docs/en/rpc/http/getepochschedule.mdx
content/docs/en/rpc/http/getfeeformessage.mdx
content/docs/en/rpc/http/getfirstavailableblock.mdx
content/docs/en/rpc/http/getgenesishash.mdx
content/docs/en/rpc/http/gethealth.mdx
content/docs/en/rpc/http/gethighestsnapshotslot.mdx
content/docs/en/rpc/http/getidentity.mdx
content/docs/en/rpc/http/getinflationgovernor.mdx
content/docs/en/rpc/http/getinflationrate.mdx
content/docs/en/rpc/http/getinflationreward.mdx
content/docs/en/rpc/http/getlargestaccounts.mdx
content/docs/en/rpc/http/getlatestblockhash.mdx
content/docs/en/rpc/http/getleaderschedule.mdx
content/docs/en/rpc/http/getmaxretransmitslot.mdx
content/docs/en/rpc/http/getmaxshredinsertslot.mdx
content/docs/en/rpc/http/getminimumbalanceforrentexemption.mdx
content/docs/en/rpc/http/getmultipleaccounts.mdx
content/docs/en/rpc/http/getprogramaccounts.mdx
content/docs/en/rpc/http/getrecentperformancesamples.mdx

Add Solana kit.js, web3.js and rust snippets to RPC docs

docs: Solana kit.js, web3.js and rust snippets

---

content/cookbook/wallets/check-publickey.mdx
content/cookbook/wallets/connect-wallet-react.mdx
content/cookbook/wallets/create-keypair.mdx
content/cookbook/wallets/generate-mnemonic.mdx
content/cookbook/wallets/generate-vanity-address.mdx
content/cookbook/wallets/restore-from-mnemonic.mdx
content/cookbook/wallets/restore-keypair.mdx
content/cookbook/wallets/sign-message.mdx
content/cookbook/wallets/verify-keypair.mdx

- update wallet section, add missing Kit/Rust snippets and enable mirror

docs: update cookbook

---

src/app/components/code/code.runnable.tsx

- add min height, short snippets were displaying with "Run" button partially covered

docs: add min height to RunnableLayout

---

content/docs/en/core/fees.mdx

- update link to triton's api documentation

docs: update triton priority fee api link

---

src/components/accelerate/AccelerateHeader.jsx

If link in the header is clicked from another page other than /accelerate, it didn't work
Fix href for links inside header
Fixes #

fix header links

---

content/guides/getstarted/how-to-create-a-token.mdx

Outdated name/url ex-Akord
Name, url, description updated
Fixes #

docs: update akord to tusky

---

content/docs/en/tokens/extensions/scaled-ui-amount/issuer-guide.mdx

- current formatting breaking Lingo translation output
- update formatting in source file to see if it fixes

docs: format scaled-ui-amount page

---

src/components/accelerate/AccelerateHeader.jsx
src/components/accelerate/AccelerateHeader.module.scss

Request to add a link to Accelerate Header
Added link to Accelerate Header
Fixes #

add link to accelerate header

---

content/cookbook/tokens/create-mint-account.mdx
content/cookbook/tokens/create-token-account.mdx
content/cookbook/tokens/get-token-mint.mdx

update following pages with missing snippets, fix broken snippets, and enable mirror
- `/create-mint-account`
- `/get-token-mint`
- `/create-token-account`

docs: update cookbook token section

---

next.config.mjs
rewrites-redirects.mjs
src/middleware.js

Set up redirect to new breakpoint SPA

Breakpoint redirect

---

src/pages/[locale]/breakpoint/side-events.js

Update bp image url to cache bust x

Cache bust x

---

content/docs/en/intro/installation.mdx

Added some AI tooling references into the installation.

feat: add ai tooling installion

---

content/cookbook/tokens/approve-token-delegate.mdx
content/cookbook/tokens/burn-tokens.mdx
content/cookbook/tokens/close-token-accounts.mdx
content/cookbook/tokens/get-all-token-accounts.mdx
content/cookbook/tokens/get-token-account.mdx
content/cookbook/tokens/get-token-balance.mdx
content/cookbook/tokens/manage-wrapped-sol.mdx
content/cookbook/tokens/mint-tokens.mdx
content/cookbook/tokens/revoke-token-delegate.mdx
content/cookbook/tokens/set-update-token-authority.mdx
content/cookbook/tokens/transfer-tokens.mdx

add token examples for cookbook using solana kit

docs(cookbook): add token examples for cookbook using solana kit

---

content/guides/getstarted/intro-to-ai.mdx

Added a section to the ai guide to high light the MCP server for ai supported development in cursor and windsurf

Add mcp tools to ai guide

---

content/docs/en/programs/deploying.mdx

broken links on `/programs/deploying` page
fix links
Fixes #
https://github.com/solana-foundation/solana-com/issues/567

docs: fix broken links program deploy page

---

content/docs/en/references/feature-gates/direct-mapping.mdx
content/docs/en/references/feature-gates/reserve-minimal-cus-for-builtins.mdx

Feat gate ref docs incorrectly state they are not yet active on mainnet
Fixes #

Update feat gate activation

---

content/docs/en/rpc/http/simulatetransaction.mdx

Fixes https://github.com/solana-foundation/solana-com/issues/553

docs: update simulatetransaction rpc page

---

content/docs/en/core/accounts.mdx
content/docs/en/core/transactions.mdx
src/app/components/code/scrollycoding.tsx
src/app/globals.css

- update `/core/accounts`
- update `/core/transactions`

docs: update accounts and transaction core concepts pages

---

content/cookbook/accounts/calculate-rent.mdx
content/cookbook/accounts/create-account.mdx
content/cookbook/accounts/get-account-balance.mdx
content/cookbook/development/connect-environment.mdx
content/cookbook/development/test-sol.mdx
content/cookbook/tokens/approve-token-delegate.mdx
content/cookbook/tokens/burn-tokens.mdx
content/cookbook/tokens/close-token-accounts.mdx
content/cookbook/tokens/create-mint-account.mdx
content/cookbook/tokens/create-token-account.mdx
content/cookbook/tokens/get-all-token-accounts.mdx
content/cookbook/tokens/get-token-account.mdx
content/cookbook/tokens/get-token-mint.mdx
content/cookbook/tokens/manage-wrapped-sol.mdx
content/cookbook/tokens/mint-tokens.mdx
content/cookbook/tokens/revoke-token-delegate.mdx
content/cookbook/tokens/set-update-token-authority.mdx
content/cookbook/tokens/transfer-tokens.mdx
content/cookbook/transactions/add-memo.mdx
content/cookbook/transactions/add-priority-fees.mdx
content/cookbook/transactions/calculate-cost.mdx
content/cookbook/transactions/offline-transactions.mdx
content/cookbook/transactions/optimize-compute.mdx
content/cookbook/transactions/send-sol.mdx
src/app/[locale]/docs/api/route.tsx
src/app/components/code/code.runnable.tsx

Updated code server to support python. 
Python snippets on cookbook runnable.

docs: enable runnable python snippets

---

src/components/developers/sections/DevelopersCoursesSection/DevelopersCoursesSection.jsx

fix: rm broken link in courses

---

public/locales/en/common.json

Suspected issue related to https://github.com/solana-foundation/solana-com/issues/548 where single quotes could be causing translation issues. Have updated to ascii chars to rule out conflicts.

fix: switch single quote chars for ascii

---

content/docs/en/programs/rust/index.mdx

- update program dependencies
- update to test with litesvm

docs: update rust hello world program

---

content/docs/en/core/transactions.mdx

Fixed typo in the documentation

---

src/app/components/inkeep/inkeep-chat-button.tsx
src/pages/_app.js

Dynamically import Inkeep Chat Button, referencing similar usage as [Inkeep Searchbar component](https://github.com/solana-foundation/solana-com/blob/main/src/app/components/inkeep/inkeep-searchbar.tsx#L9-L15).
Test to see if resolves https://github.com/solana-foundation/solana-com/issues/655

Dynamic import Inkeep Chat Button

---

content/docs/en/tokens/basics/approve-delegate.mdx
content/docs/en/tokens/basics/burn-tokens.mdx
content/docs/en/tokens/basics/close-account.mdx
content/docs/en/tokens/basics/create-mint.mdx
content/docs/en/tokens/basics/create-token-account.mdx
content/docs/en/tokens/basics/freeze-account.mdx
content/docs/en/tokens/basics/meta.json
content/docs/en/tokens/basics/mint-tokens.mdx
content/docs/en/tokens/basics/revoke-delegate.mdx
content/docs/en/tokens/basics/set-authority.mdx
content/docs/en/tokens/basics/sync-native.mdx
content/docs/en/tokens/basics/thaw-account.mdx
content/docs/en/tokens/basics/transfer-tokens.mdx

Replace instances of token-2022 in tokens section to use original SPl token program

docs(tokens): replace token-22 instances with og token program

---

public/googlec5aab0c173197075.html

Simple GA console file upload for verification with Google Console

feat: add google console auth file

---

content/docs/en/tokens/extensions/scaled-ui-amount/integration-guide.mdx

This PR adds some additional context about how indexers should process multiplier updates for historical access

add additional information about historical multiplier updates

---

apps/web/src/app/components/blog-page.tsx
apps/web/src/app/components/docs-page.tsx

fix github link on "edit page" button

docs: fix edit page github link

---

apps/web/i18n.lock

docs: Lingo Translation Update

---

apps/web/tailwind.config.js
package.json

Dev docs is broken for build on main with new `pnpm` build and deploy.
- increase `clean` script scope for better inert state pre `pnpm i`
- update target of `apps/web/tailwind.config.js` as `pnpm` resolves packages at `apps/web` root

fix: pnpm build main for developer docs

---

apps/web/next.config.ts
apps/web/package.json
apps/web/source.config.ts
apps/web/src/app/[locale]/developers/courses/[course]/[lesson]/page.tsx
apps/web/src/app/[locale]/developers/courses/[course]/page.tsx
apps/web/src/app/[locale]/docs/(main)/docs.tsx
apps/web/src/app/components/docs-layout.tsx
apps/web/src/app/components/docs-page.tsx
apps/web/src/app/opengraph/developers/[...slug]/route.ts
apps/web/src/app/sources/cookbook.ts
apps/web/src/app/sources/courses.ts
apps/web/src/app/sources/docs.ts
apps/web/src/app/sources/guides.ts
apps/web/src/app/sources/learn.ts
pnpm-lock.yaml

This reverts commit da165a782fb93ccd62f62c877b675f1340f01c84.
Causing breaking changes to production with >25% failure rate

Revert "Remove `fs-mdx` and update Fumadocs (#750)"

---

apps/web/src/component-library/video.tsx
apps/web/src/pages/[locale]/solutions/depin.tsx

Adds depin video to depin page

feat: add depin video

---

apps/web/src/app/components/api-method.tsx
apps/web/src/app/components/request-client.tsx

Output from "Try It" button partially cut off
Update UI to fully display

docs: fix rpc docs "Try It" button response display issue

---

apps/web/content/docs/en/programs/meta.json
apps/web/content/docs/en/programs/testing/meta.json
apps/web/content/docs/en/programs/testing/mollusk.mdx

Add page for testing solana programs using [mollusk](https://github.com/anza-xyz/mollusk/tree/main)

docs: add mollusk testing page
