solana-foundation/solana-com

package.json
src/utils/builderConfigs.js
yarn.lock

- Switches the field type of `quote` from `text` to `richText` to give more control over the look of the text.
- Updates solana-lib to `2.39.0` to pull updates to the RichTextQuote component so it uses `HtmlParser` to render the rich text

Update Config for RichTextQuote and update solana-lib version to 2.39.0 

---

src/utils/contentApi.ts

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape#examples

Minor: use long-form Unicode regex patterns for readability

---

next.config.js

Alias results in nextjs app dir paths to throw `TypeError: Cannot read properties of null (reading 'useContext')`
Removing following code from next.config.js fixes issue
```ts
// Alias configuration
config.resolve.alias = {
...config.resolve.alias,
react: path.resolve(__dirname, "node_modules/react"),
};
```
Code was added in [this PR](https://github.com/solana-foundation/solana-com-legacy/pull/1337). Solana-com seems to run fine with it removed.

Remove alias config causing all Nextjs App directory paths to error

---

rewrites-redirects.json

`/developers/guides/getstarted/setup-local-development` was removed and replaced with `/docs/intro/installation`
Adding redirect on solana-com repo due to limitation to `altRoutes` frontmatter on developer-content repo.

Add redirect for install page from /guide to /docs

---

src/components/ramps/Ramps.jsx

Fix a ramps display issue when in a modal. Previously the ramps data was quite scrambled when triggering the modal.

Fix ramps display issue

---

.env.example
.github/workflows/action.yml
.husky/pre-commit
package.json
src/components/ModalLauncher/ModalLauncher.js
src/components/blog/PostCard.js
src/components/news/CategorySelection.js
src/components/possible/PossibleAnimatedIcons.js
src/components/shared/Divider.js
src/components/shared/Link.js
src/pages/news/index.js
src/pages/solanaramp.js
yarn.lock

This PR adds a couple of miscellaneous updates:
- rename `format` to `format:check` for a better consistency, updated gh action and husky too
- `package.json` - remove obsolete `next-transpile-modules` dependancy and other minor updates
- updated a couple of files to ensure we get no eslint warnings or errors
- `PostCard.js` title has been updated to prevent an error when Builder return the title as a string or as an object.

Misc updates

---

src/components/shared/MarkdownRenderer/components/MarkdownTabs.module.scss

the markdown tab content's font is too small and hard to read
- boosted the font size

MarkdownTabs - font size

---

src/components/developers/DevelopersResources/DevelopersResources.jsx

filters can appear multiple times when they are listed in the dev content api with different cases
- added a case insensitive deduplication to each of the filters

fix: deduplicate filters

---

src/pages/developers/cookbook/[[...slug]].tsx
src/pages/developers/courses/[course]/[lesson]/index.tsx
src/pages/developers/guides/[...slug].tsx
src/pages/developers/resources/[...slug].jsx
src/pages/docs/[[...slug]].tsx
src/pages/docs/rpc/[[...slug]].tsx
src/utils/markdown.ts

when a markdown render error occurs, it does not display which locale had an issue
updated the github issue link to include the locale for easier troubleshooting

show locale in markdown render errors

---

package.json
yarn.lock

More:
https://github.com/vercel/next.js/security/advisories/GHSA-gp8f-8m3g-qvj9

Fix Nextjs Cache Poisoning

---

src/pages/community.js
src/utils/followerFunctions.js

This fixes https://github.com/solana-foundation/solana-com/issues/58
here the proof :

fix: cheerio import and yt scrape data

---

CONTRIBUTING.md

Add RPC providers section to `CONTRIBUTING.md`.

Add RPC providers section

---

src/data/wallets/wallet-data.js

Updated the website to the correct url fusewallet.com
Updated description as recommended to "A safe wallet for your Solana assets. 2FA. Recovery. No seed phrase."
This fixes #69.

Update details for Fuse wallet

---

src/components/header/HeaderListBuild.js

Currently goes to `/developers#courses`, but courses are on `/developers/courses`

Fix courses link

---

src/utils/markdown.ts

[This cookbook page ](https://solana.com/developers/cookbook/wallets/check-publickey) has filepath instead of name, I added file as filepath in metadata of codeblock to import files but it is getting rendered in the codeblock while can be ignored for now.

removed file metadata tag from codeblock filename regex

---

src/components/developers/sections/DevelopersDocumentsSection/DevelopersChangelog.jsx

updated the changelog description parser to handle no description and splitting based on the video description containing `---` as a separator
for future changelog video descriptions (and several past ones), we will start adding a summary paragraph at the top followed by a `---` separator so solana-com can better display
note: for other descriptions without this separator, similar video description behavior as before will occur, but just a little shorter
Fixes: #61

fix: changelog description

---

src/components/developers/sections/DevelopersHeroSection/DevelopersHeroSection.jsx
src/pages/developers/courses/index.tsx
src/pages/developers/index.jsx

- refactored the developer hero section to accept labels and button info via props
- added a hero section to the courses with some CTAs
note: instead of using the same "geometry" images at the /developers page, I used the validators geometry to add more noticeable visual difference between the two pages (/developers and /courses)
edit: the diff on the courses pages looks far more dramatic of a change than it actually is since I had to change the Layout to use the generic one to avoid clipping the courses hero. so to follow the /developers page, I wrapped the content in the same `div`

[courses] added hero to courses page

---

src/components/validators/ValidatorsFAQ.js
src/components/validators/ValidatorsGettingStarted.js
src/components/validators/ValidatorsHero.js

docs.solanalabs.com redirects to docs.anza.xyz now
This PR updates some docs.solanalabs.com docs links to point to their equivalent docs.anza.xyz pages.

Update docs links

---

src/pages/developers/cookbook/[[...slug]].tsx
src/pages/developers/courses/[course]/[lesson]/index.tsx
src/pages/developers/courses/[course]/index.tsx
src/pages/developers/courses/index.tsx
src/pages/developers/guides/[...slug].tsx
src/pages/developers/guides/index.jsx
src/pages/developers/resources/[...slug].jsx
src/pages/developers/resources/index.jsx
src/pages/docs/rpc/[[...slug]].tsx

Some pages using `revalidate` were randomly returning 404 after a while
Now that we updated to nextjs ^15, and updated node v. to 22 in Vercel, I will monitor and expecting to get rid of this annoying issue.

Reintroduce revalidate gradually

---

src/components/branding/BrandingAssets.jsx
src/components/branding/BrandingBannedLogos.jsx
src/pages/docs/[[...slug]].tsx

The SVG assets were broken in the /branding page.
Switch to `next/image` instead of the legacy and fix the SVGs display.

Fix the SVGs display in the branding page

---

src/components/developers/sections/DevelopersHeroSection/DevelopersHeroSection.module.scss

Courses page heading was not displaying in light mode due to incorrect font color used
corrected the font color in light mode 
Fixes #128

Fix: courses heading page light mode fixed

---

src/lib/builder/page/api.js
src/pages/[...slug].js

Update Builder API calls logic to avoid hanging requests that consume Vercel function resources:
- More aggressive Builder.io caching with force-cache
- Fail faster (5s for `getAllPagesWithSlug`, 8s for `getPage`)
- More reliable error handling

Builder API updates

---

next.config.js

With merging #71, we lost support for both inline SVGs and regular image SVGs
Update Webpack config to handle both inline SVGs and regular image SVGs
https://react-svgr.com/docs/webpack/

Update SVG config

---

src/pages/index.js

https://github.com/solana-foundation/solana-com/issues/148
Avoid the horizontal scroll visible on Firefox desktop - clip the overflow visible due to the hero absolute positioned elements.
Fixes #148

Avoid the horizontal scroll visible on Firefox 

---

src/app/[locale]/developers/cookbook/cookbook.tsx
src/app/[locale]/developers/courses/[course]/[lesson]/page.tsx
src/app/[locale]/developers/courses/[course]/page.tsx
src/app/[locale]/developers/courses/page.tsx
src/app/[locale]/developers/guides/[...slugs]/page.tsx
src/app/[locale]/developers/guides/page.tsx
src/app/[locale]/developers/page.tsx
src/app/[locale]/developers/resources/page.tsx
src/app/[locale]/docs/(main)/docs.tsx
src/app/[locale]/docs/rpc/rpc.tsx
src/app/[locale]/layout.tsx
src/app/metadata.ts
src/i18n/routing.ts

- some pages had wrong opengraph description
- some pages were missing translated metadata
- refactor metadata generation in app router to avoid repetition
- add missing metadata translations
- remove root layout opengraph description to avoid overriding pages' opengraph

Fix opengraph metadata

---

content/docs/intro/wallets.es.mdx
crowdin.yml

Recently migrated content files aren't managed by Crowdin.
Added new sources to `crowdin.yml`
---
This is what I think we need based on the [docs](https://support.crowdin.com/developer/configuration-file/). Since there's no way to test this before committing, maybe we should try using a subfolder first instead of the entire `/content` folder, something like `/content/docs/intro`.
One concern I have is how Crowdin handles translated files once they're committed. It’s unclear if it will ignore files like `/content/index.es.mdx` or mistakenly treat them as sources.

Add `/content` folder to Crowdin

---

public/locales/en/common.json
src/components/ai/AiHero.jsx

Missing CTA in the hero section
Add proper CTA to the AI guide `developers/guides/getstarted/intro-to-ai`

Add cta to AI guide

---

content/docs/more/meta.json
content/guides/advanced/exchange.mdx
content/guides/advanced/meta.json
rewrites-redirects.mjs
source.config.ts
src/app/[locale]/docs/(main)/docs.tsx
src/app/components/docs-page.tsx

- Move "Add Solana to your Exchange" page out of /docs into a page on /guides
- Enable [lastModifiedTime](https://fumadocs.vercel.app/docs/mdx/last-modified) for /docs to display "Last updated on Date" at bottom of page

docs: move exchange page from docs to guides

---

crowdin.yml

Crowdin GitHub integration pushes translation files even when they are 0% translated. See #162.
Add `skip_untranslated_files` to the `/content` folder file groups. 
Not sure if it's going to work since this setting isn't mentioned in the [configuration file docs](https://support.crowdin.com/developer/configuration-file/), but it's in the [CLI docs](https://crowdin.github.io/crowdin-cli/advanced#configure-export-options-for-each-file-group).

Add skip_untranslated_files to crowdin config

---

content/courses/program-optimization/program-architecture.mdx

In the source page of `Course/program-optimization/program-architecture`, the link referring to "Y2K-bug" is broken.
fix(courses): fix inaccessible link
Fixes #

fix(courses): fix inaccessible link in `Course/program-optimization/program-architecture`

---

content/docs/rpc/json-structures.mdx

- json-structures page does not mention `jsonParsed` encoding format
- add JSON Parsed section
- add reference snippets for each section
Fixes #
https://github.com/solana-foundation/solana-com/issues/171

docs: update json-structures page

---

src/app/components/docs-page.tsx

Made the docs h1 title be displayed as a link
This includes for docs, rpc, and cookbook since they all use the same `DocsPage` component

[docs/content] make the title a link

---

src/app/globals.css

Reduce docs sidebar padding because items seem too spaced out due to increasing font size from defaults

docs: reduce docs sidebar padding

---

src/app/[locale]/developers/cookbook/cookbook.tsx
src/app/[locale]/docs/(main)/docs.tsx
src/app/[locale]/docs/rpc/rpc.tsx
src/app/components/docs-page.tsx
src/app/components/giscus.tsx

Giscus would create discussion for each locale for each page.
remove locale from giscus key used to map page to [discussion](https://github.com/solana-developers/docs-feedback/discussions)

docs: remove locale from giscus to prevent duplicate discussions

---

content/docs/clients/javascript.mdx
content/docs/clients/meta.json
content/docs/clients/rust.mdx

Gutted the typescript sdk section so we can focus on keeping cookbook up to date. Updated both rust and typescript section with better installation information.

chore: update sdk pages

---

content/docs/clients/go.mdx
content/docs/clients/java.mdx
content/docs/clients/meta.json
content/docs/clients/python.mdx

Adding some additional SDK pages for the major SDKs. Mostly for CTA and to help people find them.

chore: add java, go, and python SDK pages

---

content/guides/getstarted/how-to-cpi.mdx

Went through https://solana.com/developers/guides/getstarted/how-to-cpi
and found out that docs states:
```
AccountMeta::new_readonly(account4_pubkey, true),  // writable, signer
```
and by definition of `readonly` account cannot be writable
renamed comment from `// writable, signer` to `// not writable, signer`
Fixes #

`new_readonly` is not not writable account

---

content/docs/references/clients/java.mdx

Maven docs for the Sava SDK were missing configuration needed to authenticate to the libraries hosted on github package repository.
Added example settings.xml file documentation.

Add maven settings.xml config to java.mdx

---

src/pages/_document.js

html tag is missing the lang attribute (in pages router)
Use the locale prop in _document.js to set the lang attribute

Set HTML lang attribute

---

content/courses/onchain-development/intro-to-anchor.mdx

A typo at https://github.com/solana-foundation/solana-com/blob/58f9caf2c89d8ea238f193437bb5e24c9e739f6d/content/courses/onchain-development/intro-to-anchor.mdx?plain=1#L400
Should be `AccountStruct` insted.

fix: 🐛 fixes typo in intro-to-anchor

---

content/courses/onchain-development/intro-to-anchor-frontend.mdx

Updated incorrect CLI command from create-next-dapp to create-nextjs-dapp in intro-to-anchor-frontend.mdx to match the actual command.
The Solana documentation incorrectly states that the command to create a Next.js dApp is `create-next-dapp`. However, running this command does not work.
The correct command is `create-nextjs-dapp`, as shown in the actual output.
cause actual command to create nextjs dapp is `create-nextjs-dapp` 
- Updated intro-to-anchor-frontend.mdx to replace `create-next-dapp` with `create-nextjs-dapp`.
- Ensured the correct CLI command is documented to prevent confusion for developers.
Fixes #
https://solana.com/developers/courses/onchain-development/intro-to-anchor-frontend#lab

Fix incorrect CLI command in intro-to-anchor-frontend.mdx

---

content/docs/intro/installation.mdx

- update quick install to match mucho output
- remove npx mucho install command to prevent confusion since the curl effectively does the same under the hood

docs: update install page

---

content/docs/toolkit/index.mdx
content/docs/toolkit/projects/meta.json
public/locales/en/common.json
src/app/[locale]/docs/toolkit/[[...slug]]/page.tsx
src/app/[locale]/docs/toolkit/layout.tsx
src/components/developers/DevelopersNav/DevelopersNav.jsx
src/components/header/HeaderListBuild.js

- Remove course and guides from secondary nav to minimize traffic due to amount of outdated content. Pages still accessible and linked to on /developers landing page
- Create separate page for Solana Toolkit and added link to secondary nav to try to drive more traffic to it while separating it from core /docs content

docs: create separate page for toolkit, and remove course and guide from secondary nav

---

content/docs/intro/installation.mdx

- revert because mucho doesn't install required linux dependencies

docs: revert install page changes

---

src/middleware.js

During client-side navigation nextjs thinks that href="solutions/token-extensions" should go to the catch-all "[locale]/[...slug].js" so it sends the URL params "locale=solutions&slug=token-extensions"
Remove the locale and slug params in the middleware. We only do it when the locale param isn't a valid locale, just to be extra safe.

Remove invalid search params

---

content/cookbook/wallets/check-publickey.mdx
content/cookbook/wallets/verify-keypair.mdx

- added cookbook snippets for verifying a signer/address using the new javascript client
- update "validate pubkey" to use CodeTabs

[cookbook] verify signer and address

---

content/cookbook/accounts/create-account.mdx

added cookbook snippets for creating accounts using the new javascript client

[cookbook] create account

---

content/courses/tokens-and-nfts/meta.json
content/courses/tokens-and-nfts/nfts-with-metaplex-core.mdx

**Note**: I added this PR on the developer repo before it got migrated to solana-com after talking with the Devrel team about creating a new guide on Core NFTs since the current one on NFT is quite outdated 
There wasn't any guides and courses on how to use the new Core NFT standard from Metaplex
Added the nfts-with-metaplex-core course at content/courses/tokens-and-nfts/nfts-with-metaplex-core.md with all the information about the new standard + the Lab with a full code example that is ready to use (respecting the same layout and style from the old course on token metadata NFTs)
Changed the callout at nfts-with-metaplex in content/courses/tokens-and-nfts/nfts-with-metaplex.md to link the new guide when talking about the new standard

Added a guide on Core NFTs

---

content/docs/references/feature-gates/meta.json
src/components/developers/DevelopersNav/DevelopersNav.jsx

- fix issue where both "documentation" and "toolkit" highlighted on secondary nav when toolkit section is selected
- make feature gate section default closed

docs: fix docs secondary nav UI bug

---

content/docs/references/meta.json
content/docs/references/staking/index.mdx
content/docs/references/staking/meta.json
content/docs/references/staking/stake-accounts.mdx
content/docs/references/staking/stake-program.mdx
rewrites-redirects.mjs

- Add back staking pages to docs
- Updated staking program page to link to Solana Foundation Delegation program instead of stake-o-matic (deprecated)

docs: add back staking pages

---

content/docs/references/feature-gates/c9oahlxdbm3sswtjx1ybgzpy55r2rarhmn1pbqn6hogh.mdx
content/docs/references/feature-gates/meta.json

`C9oAhLxDBm3ssWtJx1yBGzPY55r2rArHmN1pbQn6HogH` reduces 200k default CU allocation for builtins to 3k default CU
add docs explaining how devs can mitigate impact
Fixes #

Add docs for builtin default cu change

---

content/docs/core/fees.mdx

- Removing links to base transaction fee amounts. Need to clarify if this is what's actually used on network.
- https://github.com/anza-xyz/agave/blob/v2.1.13/sdk/fee-calculator/src/lib.rs#L63
- https://github.com/anza-xyz/agave/blob/v2.1.13/sdk/fee-calculator/src/lib.rs#L106

docs: remove link to fee amounts

---

.gitignore
content/docs/index.mdx
content/docs/intro/installation.mdx

- use [vale](https://vale.sh/docs) to lint content wording
- configured to use google [developer documentation style guide](https://developers.google.com/style)

docs: vale lint doc and installation pages

---

content/docs/intro/quick-start/cross-program-invocation.mdx
content/docs/intro/quick-start/deploying-programs.mdx
content/docs/intro/quick-start/index.mdx
content/docs/intro/quick-start/program-derived-address.mdx
content/docs/intro/quick-start/reading-from-network.mdx
content/docs/intro/quick-start/writing-to-network.mdx

- use [vale](https://vale.sh/docs) to lint content wording in quickstart section

docs: vale line quickstart section

---

content/docs/rpc/http/getblockcommitment.mdx

The `commitment` array refers to how much stake has lent 1-32 confirmations to a block. The array is 32 items long. This would imply that the depth ranges from 0 to 31 (zero-indexed) – not 0 to 32 as implied by the docs.
Remove the “+ 1”

Correct `commitment` property of `getBlockCommitment`

---

public/locales/en/common.json
src/pages/[locale]/events/index.jsx

Add Solanamerica calendar to better separate events and calendars on the /events page.

Add Solanamerica calendar

---

content/docs/rpc/http/getblocks.mdx

I didn't read the code, but this property is supposed to represent the latest confirmed _slot_, not the latest confirmed _block_, right? I presume that this is correct because a slot can be confirmed but have had no block produced during it.

`end_slot` in `getBlocks` represents slots, not blocks

---

content/docs/rpc/json-structures.mdx

docs: remove duplicate text in rpc transaction metadata description

---

rewrites-redirects.mjs

add redirect 
from: /docs/terminology
to: /docs/references/terminology

docs: add terminiology page redirect

---

content/docs/core/accounts.mdx
content/docs/core/programs.mdx

The documentation of programs is somewhat outdated (e.g. missing loader-v4 and core programs).
Also, there is documentation around native programs in the Agave docs which should be moved here as these are being migrated to core programs which are independent of the validator implementations.
- Updates accounts docs to reflect current state of affairs.
- Moves list of programs from docs.anza.xyz/runtime/programs here.

Docs - core/accounts and core/programs

---

content/docs/tokens/extensions.mdx
content/guides/token-extensions/interest-bearing-tokens.mdx

This change helps developers understand there are two ways to calculate accrued interest:
1. Using `uiAmountToAmountForMintWithoutSimulation` which doesn't require a transaction
2. Using `amountToUiAmount` which requires a valid signer and transaction simulation
The new method is more efficient for UI calculations where you just need to display uiAmounts as it does not need a valid signer.
- Added code example showing how to use `uiAmountToAmountForMintWithoutSimulation`
- Kept existing `amountToUiAmount` example for comparison
- Updated imports to include the new helper function
- Added a link to the token extensions guide from the TE homepage
Fixes #
- Fixed a link to the new token-2022 github

Add uiAmountToAmountForMintWithoutSimulation Example

---

content/courses/intro-to-solana/intro-to-reading-data.mdx

Add tsconfig.json block to support top-level await in TypeScript
The "Read Data From The Solana Network" guide uses top-level `await`, which can cause confusion or compiler issues without the proper TypeScript configuration (e.g., TS1378).
- Added a minimal `tsconfig.json` block to the guide
- Improves developer experience for TypeScript users
Fixes n/a

docs: add tsconfig.json guidance for top-level await in reading-from-network

---

content/docs/programs/deploying.mdx

This is a continuation of #376, the effort to merge Anza and Foundation docs about programs. 
- Merges docs.anza.xyz/cli/examples/deploy-a-program in here
- Adds program-v4 subcommands and migration
- Reorders sections by their relevance to the average dev
- Removes sections which are redundant to /core/accounts and /core/accounts

Docs - programs/deploying

---

content/guides/advanced/actions.mdx

Fixed a typographical error on guides/advanced/actions.mdx -> line 114.
A typographical error in the below line  (under section Solana Actions Execution and Lifecycle).
> The GET and POST request may return some metadata that states whether the action is capable of _be_ taken (like with the disabled field).
- Corrected a spelling error from "be" to "being" in guides/advanced/actions.mdx -> line 114 (under section Solana Actions Execution and Lifecycle).
- No other changes were made.
- This improves readability and maintains consistency.
Fixes #
```
- some metadata that states whether the action is capable of be taken (like with the disabled field). 
+ some metadata that states whether the action is capable of being taken (like with the disabled field). 
```

Fix typo in actions.mdx

---

.prettierignore
content/docs/en/rpc/http/getblock.mdx
content/docs/en/rpc/http/gettransaction.mdx
content/docs/en/rpc/websocket/blocksubscribe.mdx
src/app/components/request-client.tsx

-  update rpc curl examples to include maxSupportedTransactionVersion
-  updated pages: `getTransaction`, `getBlock`, `blockSubscribe`
- set min value to 0 for inputs that are `number` in "Try It" component

docs: update rpc curl examples to include maxSupportedTransactionVersion

---

content/docs/en/tokens/extensions/meta.json
content/docs/en/tokens/extensions/scaled-ui-amount/index.mdx
content/docs/en/tokens/extensions/scaled-ui-amount/integration-guide.mdx
content/docs/en/tokens/extensions/scaled-ui-amount/issuer-guide.mdx
content/docs/en/tokens/extensions/scaled-ui-amount/meta.json

This PR adds comprehensive documentation for the Scaled UI Amount extension, a Token-2022 feature that allows token issuers to apply an updatable multiplier to token UI amounts. This is particularly useful for scenarios like stock splits or dividend distributions.
Added three new documentation files:
1. `content/docs/en/tokens/extensions/scaled-ui-amount/index.mdx`
- Introduces the Scaled UI Amount extension
- Explains its use cases and key concepts
- Notes compatibility considerations with the interest bearing extension
2. `content/docs/en/tokens/extensions/scaled-ui-amount/issuer-guide.mdx`
- Provides very basic step-by-step instructions for creating a token with this extension
- Includes CLI examples for creating tokens with the extension
- Covers multiplier updates and balance …

Add Scaled UI Amount Extension Documentation

---

content/docs/en/tokens/extensions/scaled-ui-amount/issuer-guide.mdx

- Update snippest to use custom `terminal` lang identifier instead of `bash`
- Current syntax causing lingo translated pages to break due to parsing issue

docs: update issuer-guide page snippets

---

src/app/components/code/code.client.tsx
src/app/components/code/code.tsx

- fix issue where `<CodeTabs flags="r">` didn't render `RunnableLayout` for single code snippet

docs: Update runnable CodeTabs to work with single snippet

---

content/docs/en/tokens/extensions/scaled-ui-amount/integration-guide.mdx
content/docs/en/tokens/extensions/scaled-ui-amount/issuer-guide.mdx

- Added TypeScript code examples to the Scaled UI Amount Issuer Guide for:
- Creating a token with the Scaled UI Amount extension
- Updating the UI amount multiplier
- Fetching token balances
- Cleaned up and clarified language in the Integration Guide

Add TypeScript Examples to Scaled UI Amount Documentation

---

content/docs/en/core/fees.mdx

- Add context for transaction priority
References from Agave:
- [calculate_priority_and_cost](https://github.com/anza-xyz/agave/blob/v2.2.14/core/src/banking_stage/transaction_scheduler/receive_and_buffer.rs#L646)
- [calculate_cost](https://github.com/anza-xyz/agave/blob/master/cost-model/src/cost_model.rs#L37)
- [calculate_non_vote_transaction_cost](https://github.com/anza-xyz/agave/blob/master/cost-model/src/cost_model.rs#L113)

docs: update fee page, add context for transaction priority

---

content/docs/ar/core/fees.mdx
content/docs/de/core/fees.mdx
content/docs/el/core/fees.mdx
content/docs/en/core/fees.mdx
content/docs/es/core/fees.mdx
content/docs/fi/core/fees.mdx
content/docs/fr/core/fees.mdx
content/docs/id/core/fees.mdx
content/docs/it/core/fees.mdx
content/docs/ja/core/fees.mdx
content/docs/ko/core/fees.mdx
content/docs/nl/core/fees.mdx
content/docs/pl/core/fees.mdx
content/docs/ru/core/fees.mdx
content/docs/tr/core/fees.mdx
content/docs/uk/core/fees.mdx
content/docs/vi/core/fees.mdx
content/docs/zh/core/fees.mdx

Markdown formatting uses a different format for Priority fee links. (tables and lists)
Unify the formatting and add the Quicknode Priority fee to the list.

fix: Make format equal for all languages and add Quicknode Priority Fee

---

content/cookbook/index.mdx
content/cookbook/transactions/add-memo.mdx
content/cookbook/transactions/add-priority-fees.mdx
content/cookbook/transactions/calculate-cost.mdx
content/cookbook/transactions/offline-transactions.mdx
content/cookbook/transactions/optimize-compute.mdx
content/cookbook/transactions/send-sol.mdx

- update the existing "transactions" section of cookbook
- `/calculate-cost` and `/add-memo` aren't working on mirror for web3js and rust. May be missing dependencies on server
- `/optimize-compute` snippet isn't full example, leaving as is for now
- `/offline-transactions` page has only web3js snippets, leaving as is for now

docs: update transaction section cookbook

---

package.json
src/app/components/code/notes.tooltip.tsx
yarn.lock

- Remove the extra bottom margin in tooltips
- Better regexp support in annotations. This should work now: (note the escaped `[]` since it's a regexp)
````
```rs
// !tooltip[/#\[program\]/] example
#[program]
pub mod cookbook {
```
````
Since it's a regexp, you can even use `.` as wildcard to match any char:
````
```rs
// !tooltip[/..program./] example
#[program]
pub mod cookbook {
```
````
Related #288

Improve tooltip

---

src/app/components/code/code.client.tsx

When using `storage` with CodeTab, if there isn't a matching snippet with the same key, none get rendered.
- Default to first tab if the stored tab title no longer exists.
Related #288

Fix selected tab when stored title doesn't exist

---

content/guides/getstarted/how-to-create-a-token.mdx

The Tusky description was cutoff in the previous [PR](https://github.com/solana-foundation/solana-com/pull/485) merge. The description now sounds like all files are only hosted for 30 days, which is very misleading.
New Tusky description is added.
Fixes #
Docs updated.

docs: Update Tusky description for clarity

---

src/app/components/code/code.runnable.tsx

- remove link to mirror.ad in runnable code component
- mirror is no longer maintained, and one less link for readers to bounce from page
- currently looking into alternative for running code on docs using [txtx'](https://github.com/txtx/surfpool)s surfnet service

docs: remove link to mirror

---

content/docs/en/tokens/extensions/scaled-ui-amount/issuer-guide.mdx

This PR updates the TypeScript example in the Scaled UI Amount Issuer Guide to ensure the effectiveTimestamp passed to the multiplier update uses seconds (via Math.floor(Date.now() / 1000)) instead of milliseconds. This matches the expected precision for the Solana program and prevents incorrect future timestamps.
No other logic or documentation was changed.

Fix scaled ui effective timestamp to use seconds instead of milliseconds

---

rewrites-redirects.mjs

Removes active redirect to `/breakpoint/speakers` which will be live on the new BP25 site.

fix: remove speakers redirect

---

src/components/learn/mobile-chapter-navigation.tsx

There is a transparency issue with the current mobile chapter navigation. This fixes it.
Before:
after:
css tweaks
Fixes #

fix: transparency in the chapter nav

---

public/locales/en/common.json
src/components/header/HeaderList.js
src/components/header/HeaderListLearn.js

As @h4rkl pointed, the first implementation of the learn menu was hiding some key SEO pages. This reworks the menu to align it more to the current other menus
- bring 4 links into a drop down instead
Fixes #

feat: rework learn menu

---

content/docs/en/tokens/extensions/confidential-transfer/apply-pending-balance.mdx
content/docs/en/tokens/extensions/confidential-transfer/create-mint.mdx
content/docs/en/tokens/extensions/confidential-transfer/create-token-account.mdx
content/docs/en/tokens/extensions/confidential-transfer/deposit-tokens.mdx
content/docs/en/tokens/extensions/confidential-transfer/index.mdx
content/docs/en/tokens/extensions/confidential-transfer/transfer-tokens.mdx
content/docs/en/tokens/extensions/confidential-transfer/withdraw-tokens.mdx

ZK Elgamal program currently disabled as it undergoes security audit.
Add warning to docs pages.

docs: add warning to confidential transfer pages, zk program disable

---

src/app/components/code/code.runnable.tsx

disable runnable component for python related to https://github.com/solana-foundation/solana-com/pull/622, server does not support python code

docs: disable runnable component for python code

---

src/components/developers/DevelopersContentPage/DevelopersContentPage.tsx

Small fix to update opengraph images which are failing to load if the URL contains i18n path segment - eg. `/en/`

fix: remove i18n url segment from opengraph images

---

content/guides/advanced/actions.mdx

The LinkedAction interface is missing a field: type
Adds the type field to the LinkedAction interface
Fixes #

docs(actions & blinks): Add type field to LinkedAction type

---

content/docs/en/intro/installation.mdx

coral-xyz references in documentation might raise alarm for new developers.
Fixes #

Replaced coral-xyz with solana-foundation in repo references

---

src/app/components/code/code.tsx
src/app/globals.css

In Arabic where RTL lang format is used for i18n this PR enforces LTR for semantically correct codeblocks.
- fumadocs styles for all `code` and `pre` codeblocks
- Tailwind styling in `<Code />` component

feat: add styling for LTR enforcement of all code blocks

---

src/components/LanguageSelector.js

The language selector’s dropdown was overflowing past the footer, and users also couldn’t scroll to see all available languages in alternate solution.
- Added inline styles to <Dropdown.Menu> to avoid overflow and added constraints to enable vertical scrolling when content exceeds that height
This ensures the menu is never cut off and remains fully scrollable.
Fixes issue no. #554 
thanks!

fix #554: Language selector dropdown menu breaking footer

---

apps/web/content/docs/en/core/transactions.mdx

There was a missing 's'
I added the missing 's'

Fixing a typo in the Solana docs

---

apps/web/content/docs/en/intro/quick-start/reading-from-network.mdx

Small grammatical error by missing a word which makes docs seem more unprofessional
Added the missing word 'is' to fix the sentence

docs: fixed missing 'is' in sentence about data persistence

---

apps/web/content/docs/en/tokens/basics/transfer-tokens.mdx

Documentation contains "tokenaccounts" as one word instead of the correct "token accounts" with proper spacing.
Corrected "tokenaccounts" to "token accounts" for proper spacing and readability

docs: Fix typo "tokenaccounts" to "token accounts"

---

apps/web/package.json
package.json
pnpm-lock.yaml

Husky was configured in `apps/web` but it's supposed to run in the project root.
Before:
After:

chore: move husky to repo root

---

package.json
pnpm-lock.yaml

We depend on [seti-icons](https://www.npmjs.com/package/seti-icons) to render the filetype icons in the RPC docs. Somewhere down it's dependencies it pulls in `nth-check@1.0.2`.
Pin the version so we only depend on `nth-check@2.1.1`:
```diff
$ pnpm why -r nth-check
Legend: production dependency, optional only, dev only
solana-com@3.0.0 /Users/beeman/dev/solana-foundation/solana-com/apps/web
dependencies:
cheerio 1.1.2
└─┬ cheerio-select 2.1.0
└─┬ css-select 5.2.2
└── nth-check 2.1.1
seti-icons 0.0.4
└─┬ svgo 1.3.2
└─┬ css-select 2.1.0
-    └── nth-check 1.0.2
+    └── nth-check 2.1.1
devDependencies:
@svgr/webpack 8.1.0
└─┬ @svgr/plugin-svgo 8.1.0
└─┬ svgo 3.3.2
└─┬ css-select 5.2.2
└── nth-check 2.1.1
```
Fixes https://github.com/solana-foundation/solana-com/security/dependabot/33

chore: pin nth-check version to 2.1.1

---

apps/web/src/components/branding/BrandingAssets.jsx
apps/web/src/pages/[locale]/branding.js

The branding page had some SEO hiccups: generic alt text on logos making them hard for search engines to differentiate, no structured data for better visibility, missing thumbnails in Google results, and the guidelines PDF hosted externally on Google Drive, which hurt our control over SEO.
- Spruced up alt text on logos to be more descriptive (e.g., "Official Solana full logo (horizontal)").
- Added JSON-LD structured data for the logos to help with rich search results.
- Set a specific og:image to get thumbnails showing up in SERPs.
- Switched the guidelines PDF link to an internal path for better SEO (add the file to public dir).
Fixes the issues from the September 2025 SEO Cleanup Campaign doc.

chore: seo cleanup for branding and logos

---

apps/web/src/components/universities/UniversityEventsGrid.tsx

- Replaced broken Ann Arbor MHacks event image URL with a working Unsplash image
- The new image shows University of Michigan buildings with architectural details
- Updated the image URL for the MHacks event in `UniversityEventsGrid.tsx`
- Changed from a broken URL to: https://images.unsplash.com/photo-1579055632087-a025815989ed
- The URL format now matches the pattern used by other event images (photo-{id}?q=80&w=2000)
- Verified the new image URL is accessible and loads correctly
- Confirmed the URL follows the same format as other working images in the file

fix: replace broken Ann Arbor MHacks event image

---

apps/web/content/docs/en/core/accounts.mdx

Small grammar mistake in the Accounts doc: 
_"For non-executable accounts, this generally stores state that's meant be read from."_
Missing "to" after "meant"
Added missing "to"

fix: Grammar mistake in accouts.mdx

---

apps/web/src/app/components/code/scrollycoding.tsx

The intersection observer from the ScrollyCoding component wasn't triggering when the browser height wasn't large enough.
Give more space to the `rootMargin`

Fix scrollycoding `rootMargin`

---

.gitignore
apps/web/next.config.ts

Vercel is failing because the serverless functions are exceeding 250mb
We don't need the content and public files in the serverless functions build
Fixes #
Documented in code

fix: vercel build size

---

apps/web/content/docs/en/rpc/http/getprogramaccounts.mdx

- add link to [filter criteria](https://solana.com/docs/rpc#filter-criteria) on getprogramaccounts rpc page

docs: add filter criteria link to getprogramaccounts rpc page
